Repository h2oai/wave-ml, pull requests merged in 2021-06, with the labels that each got.

#59 Detect and force type to categorical for `H2O-3` predictions
  h2o_wave_ml/h2o3.py
  h2o_wave_ml/ml.py
Labels: type/bug

#60 Check for `scorer` in `params` directly
  h2o_wave_ml/dai.py
Labels: type/refactoring

#64 Add function to download `autodoc`
  h2o_wave_ml/dai.py
  h2o_wave_ml/h2o3.py
  h2o_wave_ml/types.py
  h2o_wave_ml/utils.py
Labels: type/feature

#67 Remove MLOps related return types
  h2o_wave_ml/dai.py
  h2o_wave_ml/utils.py
Labels: type/bug

#68 Add H2O Wave ML Demo App for H2O AI Hybrid Cloud
  .gitignore
  h2o_wave_ml_app/.appignore
  h2o_wave_ml_app/LongDescription.md
  h2o_wave_ml_app/__init__.py
  h2o_wave_ml_app/app.toml
  h2o_wave_ml_app/requirements.txt
  h2o_wave_ml_app/snippets/get_model.py
  h2o_wave_ml_app/snippets/list_dai_multinode_clusters.py
  h2o_wave_ml_app/snippets/list_dai_single_instances.py
  h2o_wave_ml_app/snippets/load_model.py
  h2o_wave_ml_app/snippets/save_autodoc.py
  h2o_wave_ml_app/snippets/save_model.py
  h2o_wave_ml_app/snippets/score_model.py
  h2o_wave_ml_app/snippets/train_model.py
  h2o_wave_ml_app/src/__init__.py
  h2o_wave_ml_app/src/app.py
  h2o_wave_ml_app/src/cards.py
  h2o_wave_ml_app/src/layouts.py
  h2o_wave_ml_app/static/architecture_dark.png
  h2o_wave_ml_app/static/architecture_light.png
  h2o_wave_ml_app/static/icon.png
  h2o_wave_ml_app/static/screenshot-1.png
  h2o_wave_ml_app/static/screenshot-2.png
  h2o_wave_ml_app/static/screenshot-3.png
  h2o_wave_ml_app/static/screenshot-4.png
Labels: pr/feature
